name: Build and Deploy WebApp

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main
    # paths:
    #   - 'verseSketch-frontend/**'
    #   - 'VerseSketch.Backend/**'
    #   - 'Dockerfile'
    #   - '.github/workflows/pushAndUpdateWebApp.yml'
  workflow_dispatch:

env:
  ACR_NAME: docker.io/sircalibrik
  IMAGE_NAME: versesketch
  APP_NAME: VerseSketch
  RESOURCE_GROUP: VerseSketch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get tag as version
        id: versioning
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -n 's|refs/tags/v||p')
          echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image with version
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:webapp-${{ env.IMAGE_TAG }}
          file: ./Dockerfile
          
      - name: Build and push Docker image with latest
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:webapp-latest
          file: ./Dockerfile

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Azure App Service
        run: |
          az webapp sitecontainers update \
          --name ${{ env.APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --container-name main --image ${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:webapp-${{ env.IMAGE_TAG }} \
          --target-port 80 --is-main true
